export const AGENCES: string[] = [
  "Albi","Arcachon","Aulnay-sous-bois","Aurillac","Auxerre","Begles",
  "Bordeaux Meriadeck","Bourges","Brest","Brestphare","Bretigny","Cergy",
  "Cesson Bois-senart","Champfleury","Claye Souilly","Clermont-Ferrand",
  "Collegien Bay2","Creil","Creteil","Dieppe","Dijon","Dreux","Englos",
  "Epernay","Evry2","Farebersviller","Flins","Fontenay-sous-Bois","Glissy",
  "Grenoble","Herouville-saint-Clair","La Defense","Lanester","Le Havre",
  "Le Mans","Leers","Lens","Les Ulis","Lieussaint Carre-Senart",
  "Lille Euralille","Louvroil","Lyon Part-Dieu","Lyon Victor-Hugo",
  "Mandelieu-La-Napoule","Marsac-Perigueux","Marseille Grand Littoral",
  "Marseille TDP","Maurepas","Meaux","Montesson","Nancy","Nantes Cassard",
  "Noisy","Orange","Orleans","Orvault","Paris Bonne-Nouvelle",
  "Paris Chaussee Antin","Paris Sebastopol","Paris Voltaire","PERPIGNAN",
  "Plaisir","Poitiers","Quimper","Rennes","Roissy","Roncq","Rosny2","Rouen",
  "Saint-Avold","Saint-Etienne Centre2","Saint-Genis","Saint-Gregoire",
  "Saint-Laurent-du-Var","Saint-Martin-Boulogne","Saint-Orens",
  "Saint-Pierre-d-Irube","Saint-Priest","Saint-Quentin","Soissons",
  "Thiais Belle-Epine","Toulon","Toulouse","Tours","Val d'europe",
  "Valenciennes","Velizy","Villeneuve-d-Asq","Villeneuve-la-Garenne Qwartz",
  "Villiers-en-biere","Vitrolles",
];
